### ISSUE TITLE
tracker ID changes

### ISSUE THREAD

**Issue by hadign20** [gabilodeau/MKCF#1]
I am trying to use your multi-tracker in a traffic video with small vehicles. It works well, but the tracking ID for each unique vehicle changes a lot without the vehicle being occluded or anything. I changed the parameters in main:
```

//Parameters

int Merge_threshold = 2000;     // square     example, 20^2=400.

int Min_blob_size = 10;

int UnmatchedDuration = 8;

int minTrackLength = 12;
```

The ID for each vehicle changes rapidly. Is there a parameter I should change?

**Comment by gabilodeau** [comment]
I think it could be caused by the size of the vehicles. To track successfully, a vehicle should be detected every "UnmatchedDuration" frame. That is, the tracker predicts no more than 8 frames. If the detected vehicle blob is filtered out because it is smaller than  Min_blob_size, the track for that object would be lost. It depends how small the vehicles are... If not, may be it is the Merge_threshold that should be made smaller. This is to merge two nearby objects (to solve fragmentation problems). If you don't have vehicles that are fragmented into several parts, this value could be made very low. Merging blobs change their appearance, and track could be lost. 

minTrackLength is use to delete tracks that are too short.

**Comment by hadign20** [comment]
Thank you for the great explaination! Now it works
